import os
import sys

# Add project root to PYTHONPATH so 'app' can be imported
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pandas as pd
from datasets import Dataset
from dotenv import load_dotenv
from ragas import evaluate
from ragas.metrics import (
    Faithfulness,
    AnswerRelevancy,
    LLMContextPrecisionWithReference,
    LLMContextRecall
)
from ragas.llms import LangchainLLMWrapper
from ragas.embeddings import LangchainEmbeddingsWrapper
from langchain_openai import ChatOpenAI, OpenAIEmbeddings

# Import our RAG service
from app.services.rag_service import rag_service

load_dotenv()

def run_evaluation():
    testset_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "data", "rag_testset.csv")
    
    if not os.path.exists(testset_path):
        print(f"Test set not found at {testset_path}. Please run generate_test_set.py first.")
        return

    print(f"Loading test set from {testset_path}...")
    df = pd.read_csv(testset_path)
    
    # Check the columns generated by TestsetGenerator. Usually they are:
    # user_input, reference_context, reference, eval_type
    if "user_input" not in df.columns:
        print("Expected 'user_input' column in the test set. Check format.")
        return

    questions = df["user_input"].tolist()
    references = df["reference"].tolist() if "reference" in df.columns else [""] * len(questions)
    
    responses = []
    retrieved_contexts = []
    
    print(f"Evaluating {len(questions)} queries against our RAG pipeline...")
    for q in questions:
        # Retrieve candidates
        initial_k = 15
        n_results = 3
        
        results = rag_service.collection.query(
            query_texts=[q],
            n_results=initial_k,
            include=['documents']
        )
        candidate_texts = []
        if results.get("documents") and results["documents"][0]:
            candidate_texts.extend(results["documents"][0])
            
        if rag_service.bm25_retriever:
            rag_service.bm25_retriever.k = initial_k
            bm25_docs = rag_service.bm25_retriever.invoke(q)
            for d in bm25_docs:
                if d.page_content not in candidate_texts:
                    candidate_texts.append(d.page_content)
                    
        # Rerank
        if candidate_texts:
            cross_inp = [[q, text] for text in candidate_texts]
            scores = rag_service.reranker.predict(cross_inp)
            scored_texts = sorted(zip(scores, candidate_texts), key=lambda x: x[0], reverse=True)
            texts = [text for score, text in scored_texts[:n_results]]
        else:
            texts = []
            
        # Get answer
        # Since we just want the response string, we can use the rag_service.get_answer directly
        # but since we already retrieved the contexts, we'll store them.
        ans = rag_service.get_answer(q, n_results=n_results)
        
        responses.append(ans)
        retrieved_contexts.append(texts)

    # Format for Ragas evaluate
    # Ragas v0.4.x expects: user_input, response, retrieved_contexts, reference
    eval_data = {
        "user_input": questions,
        "response": responses,
        "retrieved_contexts": retrieved_contexts,
        "reference": references,
    }
    
    eval_dataset = Dataset.from_dict(eval_data)
    
    if not os.getenv("OPENAI_API_KEY"):
        print("Error: OPENAI_API_KEY is not set. Cannot run Ragas evaluation.")
        return
        
    llm = ChatOpenAI(model="gpt-4o-mini")
    evaluator_llm = LangchainLLMWrapper(llm)
    
    emb = OpenAIEmbeddings(model="text-embedding-3-small")
    evaluator_embeddings = LangchainEmbeddingsWrapper(emb)

    ragas_metrics = [
        AnswerRelevancy(), 
        LLMContextPrecisionWithReference(), 
        LLMContextRecall(), 
        Faithfulness()
    ]

    print("Running Ragas Evaluation (this will call OpenAI APIs)...")
    try:
        results = evaluate(
            dataset=eval_dataset,
            metrics=ragas_metrics,
            llm=evaluator_llm,
            embeddings=evaluator_embeddings
        )
        
        results_df = results.to_pandas()
        results_df.to_csv("data/evaluation_report.csv", index=False)
        print("\nEvaluation complete! Results saved to data/evaluation_report.csv\n")
        
        print("Summary Scores:")
        for metric in ["answer_relevancy", "llm_context_precision_with_reference", "context_recall", "faithfulness"]:
            if metric in results_df.columns:
                print(f"- {metric}: {results_df[metric].mean():.4f}")
        
    except Exception as e:
        print(f"\nEvaluation failed: {str(e)}")

if __name__ == "__main__":
    run_evaluation()
