from pydantic import BaseModel, Field

class ChatRequest(BaseModel):
    query: str = Field(..., description="The medical question or prompt from the user.")
    
class ChatResponse(BaseModel):
    response: str = Field(..., description="The grounded answer generated by the RAG system.")
