from pydantic import BaseModel, Field

from typing import Optional

class ChatRequest(BaseModel):
    query: str = Field(..., description="The medical question or prompt from the user.")
    session_id: Optional[str] = Field(None, description="The chat session ID")
    
class ChatResponse(BaseModel):
    response: str = Field(..., description="The grounded answer generated by the RAG system.")
